// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUB-uN6fdDmX0FF6Q-eQw8CvS-enhL0Wk',
    appId: '1:57655670337:web:a723cd7dbc06ceab1ff8c0',
    messagingSenderId: '57655670337',
    projectId: 'attendence-management-sy-9d181',
    authDomain: 'attendence-management-sy-9d181.firebaseapp.com',
    storageBucket: 'attendence-management-sy-9d181.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3ndNpY6p-OSwsaA-PK0a5UBncWL0HOo',
    appId: '1:57655670337:android:d3e7b584e43a07ff1ff8c0',
    messagingSenderId: '57655670337',
    projectId: 'attendence-management-sy-9d181',
    storageBucket: 'attendence-management-sy-9d181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9Dm1eCH_OTFtiT91XBL5VWR6feT9G-c',
    appId: '1:57655670337:ios:c7423e8c45032cd81ff8c0',
    messagingSenderId: '57655670337',
    projectId: 'attendence-management-sy-9d181',
    storageBucket: 'attendence-management-sy-9d181.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9Dm1eCH_OTFtiT91XBL5VWR6feT9G-c',
    appId: '1:57655670337:ios:c7423e8c45032cd81ff8c0',
    messagingSenderId: '57655670337',
    projectId: 'attendence-management-sy-9d181',
    storageBucket: 'attendence-management-sy-9d181.firebasestorage.app',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUB-uN6fdDmX0FF6Q-eQw8CvS-enhL0Wk',
    appId: '1:57655670337:web:686ecbe26b45d5f41ff8c0',
    messagingSenderId: '57655670337',
    projectId: 'attendence-management-sy-9d181',
    authDomain: 'attendence-management-sy-9d181.firebaseapp.com',
    storageBucket: 'attendence-management-sy-9d181.firebasestorage.app',
  );
}
